### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

### ISSUE THREAD

**Issue by inudder** [hcodes/server_yametrika#11]
Во время установки `composer require hcodes/server_yametrika`
Информация в консоли содержит Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Игнорировать это сообщение или как фиксить? 

Использую вариант интеграции следующий:
```
<?php
require_once('yametrika.php');
$counter = new YaMetrika(57098764);
$counter->hit();
?>
```

Скажите пожалуйста для чего такой вариант?  
` $counter->hit('https://mysite.org', 'Main page', 'https://ya.ru');  `

В каких случаях такой вариант использовать? Я должен подставить свой урл вместо https://mysite.org?

**Comment by hcodes** [comment]
```php
$counter->hit();
```
Все параметры автоматически вычисляются из $_SERVER.

```php
$counter->hit('https://mysite.org', 'Main page', 'https://ya.ru');
```
А здесь параметры явно передаются.
Первый параметр: текущий URL страницы.
Второй: заголовок страницы.
Третий: реферер.

**Comment by hcodes** [comment]
Про ошибки с zendframework посмотрю позже.

**Comment by hcodes** [comment]
> Информация в консоли содержит Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
> Игнорировать это сообщение или как фиксить?

У данного пакета есть только [dev-зависимости](https://github.com/hcodes/server_yametrika/blob/master/composer.json#L21).

**Comment by hcodes** [comment]
```
composer require hcodes/server_yametrika
Using version ^2.0 for hcodes/server_yametrika
./composer.json has been created
Running composer update hcodes/server_yametrika
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking hcodes/server_yametrika (v2.0.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading hcodes/server_yametrika (v2.0.2)
  - Installing hcodes/server_yametrika (v2.0.2): Extracting archive
Generating autoload files
```
