### ISSUE TITLE
Как интегрировать счетчик на виртуальном хостинге?

### ISSUE THREAD

**Issue by inudder** [hcodes/server_yametrika#13]
В новой версии установка через composer, скачать архив и использовать файл YaMetrika.php тоже можно на виртуальном хостинге, но интеграция для новой версии отличается?
Раньше я использовал так

require_once('YaMetrika.php');
$counter = new YaMetrika(57098743);
$counter->hit();

**Теперь только так**

require_once('YaMetrika.php');
**use ServerYaMetrika\YaMetrika;**
$counter = new YaMetrika(57098755);
$counter->hit();

Если не прописать use ServerYaMetrika\YaMetrika; , то отдает 500 ошибку. 

@hcodes

**Comment by inudder** [comment]
Лог
2021/03/12 19:28:52 [error] 920#920: *56 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "YaMetrika" not found in /home/admin/web/site.ru/public_html/wp-content/plugins/d/d_ii.php(15) : eval()'d code:4
Stack trace:
#0 /home/admin/web/site.ru/public_html/wp-content/plugins/d/d_ii.php(15): eval()
#1 /home/admin/web/site.ru/public_html/index.php(2): include('...')
#2 {main}
  thrown in /home/admin/web/site.ru/public_html/wp-content/plugins/d/d_ii.php(15) : eval()'d code on line 4" while reading response header from upstream, client: 213.87.224.159, server: site.ru, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm-site.ru.sock:", host: "site.ru"

В вашем примере обновленном предлагается юзать use ServerYaMetrika\YaMetrika; но ведь нужно указать где файлик лежит YaMetrika.php , вот и я дошел до варианта  require_once('YaMetrika.php');
use ServerYaMetrika\YaMetrika;
$counter = new YaMetrika(57098755);
$counter->hit(); 

Это правильно?

**Comment by hcodes** [comment]
Да.

**Comment by hcodes** [comment]
Страндартное подключение через Composer.
