### ISSUE TITLE
Почему-то не работает

### ISSUE THREAD

**Issue by eleimt** [hcodes/server_yametrika#15]
Здравствуй
Делаю так:
```
require_once __DIR__ . '/vendor/autoload.php';

use ServerYaMetrika\YaMetrika;

$counter = new YaMetrika(******);

$hit  = $counter->hit('/index.html', 'Site', 'https://ya.ru');
$goal = $counter->reachGoal('test');
```
У обоих ответ true, но в Аналитике ничего. Подскажи, что не так. Спасибо.

**Comment by hcodes** [comment]
А в настройках счётчика роботы включены? Должно быть так:
<img width="934" alt="изображение" src="https://user-images.githubusercontent.com/157520/113404969-b62f9c00-93b1-11eb-969b-a46d3427890d.png">

**Comment by eleimt** [comment]
@hcodes Ну конечно нет :) Спасибо большое.

**Comment by eleimt** [comment]
@hcodes Что-то всё равно, не приходит..

**Comment by hcodes** [comment]
Вечером постараюсь посмотреть.

**Comment by eleimt** [comment]
@hcodes Подскажи пожалуйста, есть возможность отправить цель JS'ом? Без установки счётчика необходимо.

**Comment by hcodes** [comment]
Нашёл ошибку в двойном кодировании параметров.

**Comment by eleimt** [comment]
@hcodes Ок, буду ждать обнову. Подскажи еще по JS, есть ли возможность эту отправку реализовать?

**Comment by hcodes** [comment]
Есть небольшой пакет для этого: https://github.com/hcodes/lyam#%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0-%D1%86%D0%B5%D0%BB%D0%B8

**Comment by eleimt** [comment]
@hcodes Огонь. Спасибо.

**Comment by hcodes** [comment]
Поправил, v2.0.2.
