### ISSUE TITLE
Можно ли обойтись без обратного слеша при Юзинге ? use ServerYaMetrika\YaMetrika;

### ISSUE THREAD

**Issue by inudder** [hcodes/server_yametrika#18]
Собственно вопрос. Хочу интегрировать код в WP через плагин https://ru.wordpress.org/plugins/code-snippets-extended/
Но при вставки, use ServerYaMetrika\YaMetrika;  обрезается обратный слеш и получается use ServerYaMetrikaYaMetrika; (дело понятно не в вашей разработки и не в параметрах PHP, какая - то не совершенность плагин, вот и думаю как можно закостылить)

**Comment by hcodes** [comment]
Я бы написал автору плагина.
![image](https://user-images.githubusercontent.com/157520/152006856-fdb40b46-28ad-4004-a902-b70697325f05.png)
